/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSignalsRouteImport } from './routes/_app/signals'
import { Route as AppScannerRouteImport } from './routes/_app/scanner'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppEaRouteImport } from './routes/_app/ea'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as ApiPublicCronSignalsRouteImport } from './routes/api/public/cron.signals'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSignalsRoute = AppSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AppRoute,
} as any)
const AppScannerRoute = AppScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppEaRoute = AppEaRouteImport.update({
  id: '/ea',
  path: '/ea',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicCronSignalsRoute = ApiPublicCronSignalsRouteImport.update({
  id: '/api/public/cron/signals',
  path: '/api/public/cron/signals',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/account': typeof AppAccountRoute
  '/ea': typeof AppEaRoute
  '/inbox': typeof AppInboxRoute
  '/scanner': typeof AppScannerRoute
  '/signals': typeof AppSignalsRoute
  '/api/public/cron/signals': typeof ApiPublicCronSignalsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/account': typeof AppAccountRoute
  '/ea': typeof AppEaRoute
  '/inbox': typeof AppInboxRoute
  '/scanner': typeof AppScannerRoute
  '/signals': typeof AppSignalsRoute
  '/': typeof AppIndexRoute
  '/api/public/cron/signals': typeof ApiPublicCronSignalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/ea': typeof AppEaRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/scanner': typeof AppScannerRoute
  '/_app/signals': typeof AppSignalsRoute
  '/_app/': typeof AppIndexRoute
  '/api/public/cron/signals': typeof ApiPublicCronSignalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/plans'
    | '/register'
    | '/account'
    | '/ea'
    | '/inbox'
    | '/scanner'
    | '/signals'
    | '/api/public/cron/signals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/plans'
    | '/register'
    | '/account'
    | '/ea'
    | '/inbox'
    | '/scanner'
    | '/signals'
    | '/'
    | '/api/public/cron/signals'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/plans'
    | '/register'
    | '/_app/account'
    | '/_app/ea'
    | '/_app/inbox'
    | '/_app/scanner'
    | '/_app/signals'
    | '/_app/'
    | '/api/public/cron/signals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRoute
  RegisterRoute: typeof RegisterRoute
  ApiPublicCronSignalsRoute: typeof ApiPublicCronSignalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signals': {
      id: '/_app/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof AppSignalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scanner': {
      id: '/_app/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AppScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ea': {
      id: '/_app/ea'
      path: '/ea'
      fullPath: '/ea'
      preLoaderRoute: typeof AppEaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/cron/signals': {
      id: '/api/public/cron/signals'
      path: '/api/public/cron/signals'
      fullPath: '/api/public/cron/signals'
      preLoaderRoute: typeof ApiPublicCronSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppEaRoute: typeof AppEaRoute
  AppInboxRoute: typeof AppInboxRoute
  AppScannerRoute: typeof AppScannerRoute
  AppSignalsRoute: typeof AppSignalsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppEaRoute: AppEaRoute,
  AppInboxRoute: AppInboxRoute,
  AppScannerRoute: AppScannerRoute,
  AppSignalsRoute: AppSignalsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  RegisterRoute: RegisterRoute,
  ApiPublicCronSignalsRoute: ApiPublicCronSignalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
